<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return apply_filters(
	'wcv_sc_settings',
	array(
		'enabled'                     => array(
			'title'       => __( 'Enable/Disable', 'wc-vendors-gateway-stripe-connect' ),
			'label'       => __( 'Enable Stripe connect', 'wc-vendors-gateway-stripe-connect' ),
			'type'        => 'checkbox',
			'description' => '',
			'default'     => 'no',
		),
		'title'                       => array(
			'title'       => __( 'Title', 'wc-vendors-gateway-stripe-connect' ),
			'type'        => 'text',
			'description' => __( 'This controls the title which the user sees during checkout.', 'wc-vendors-gateway-stripe-connect' ),
			'default'     => __( 'Credit Card (Stripe)', 'wc-vendors-gateway-stripe-connect' ),
			'desc_tip'    => true,
		),
		'description'                 => array(
			'title'       => __( 'Description', 'wc-vendors-gateway-stripe-connect' ),
			'type'        => 'text',
			'description' => __( 'This controls the description which the user sees during checkout.', 'wc-vendors-gateway-stripe-connect' ),
			'default'     => 'Pay with your credit card via Stripe.',
			'desc_tip'    => true,
		),
		'testmode'                    => array(
			'title'       => __( 'Test mode', 'wc-vendors-gateway-stripe-connect' ),
			'label'       => __( 'Enable Test Mode', 'wc-vendors-gateway-stripe-connect' ),
			'type'        => 'checkbox',
			'description' => __( 'Place the payment gateway in test mode using test API keys.', 'wc-vendors-gateway-stripe-connect' ),
			'default'     => 'yes',
			'desc_tip'    => true,
		),
		'publishable_key'             => array(
			'title'       => __( 'Publishable Key', 'wc-vendors-gateway-stripe-connect' ),
			'type'        => 'password',
			'class'       => 'stripe-connect-key live-key',
			'description' => __( 'Get your API keys from your stripe account.', 'wc-vendors-gateway-stripe-connect' ),
			'default'     => '',
			'desc_tip'    => true,
		),
		'secret_key'                  => array(
			'title'       => __( 'Secret Key', 'wc-vendors-gateway-stripe-connect' ),
			'type'        => 'password',
			'class'       => 'stripe-connect-key live-key',
			'description' => __( 'Get your API keys from your stripe account.', 'wc-vendors-gateway-stripe-connect' ),
			'default'     => '',
			'desc_tip'    => true,
		),
		'client_id'                   => array(
			'title'       => __( 'Client ID', 'wc-vendors-gateway-stripe-connect' ),
			'type'        => 'text',
			'description' => __( 'Get your client ID from your stripe account, the Apps menu.', 'wc-vendors-gateway-stripe-connect' ),
			'default'     => '',
			'desc_tip'    => true,
		),
		'test_publishable_key'        => array(
			'title'       => __( 'Test Publishable Key', 'wc-vendors-gateway-stripe-connect' ),
			'type'        => 'password',
			'class'       => 'stripe-connect-key test-key',
			'description' => __( 'Get your API keys from your stripe account.', 'wc-vendors-gateway-stripe-connect' ),
			'default'     => '',
			'desc_tip'    => true,
		),
		'test_secret_key'             => array(
			'title'       => __( 'Test Secret Key', 'wc-vendors-gateway-stripe-connect' ),
			'type'        => 'password',
			'class'       => 'stripe-connect-key test-key',
			'description' => __( 'Get your API keys from your stripe account.', 'wc-vendors-gateway-stripe-connect' ),
			'default'     => '',
			'desc_tip'    => true,
		),
		'test_client_id'              => array(
			'title'       => __( 'Test Client ID', 'wc-vendors-gateway-stripe-connect' ),
			'type'        => 'text',
			'description' => __( 'Get your client ID from your stripe account, the Apps menu.', 'wc-vendors-gateway-stripe-connect' ),
			'default'     => '',
			'desc_tip'    => true,
		),
		'redirect_uri'                => $this->get_option( 'redirect_uri' ) ? array(
			'title'       => __( 'Connect redirect page', 'wc-vendors-gateway-stripe-connect' ),
			'type'        => 'select',
			'description' => $this->get_option( 'redirect_uri' ) ? sprintf(
				'%s<br/>%s<br />%s<code class="redirect-uri-value click-to-select-all">%s</code> (%s)',
				__( 'Select the page to redirect to after a vendor account is connected.', 'wc-vendors-gateway-stripe-connect' ),
				__( 'Stripe requires this URI exactly matches one of the uris specified in Stripe settings.', 'wc-vendors-gateway-stripe-connect' ),
				__( 'Please use this URI for Stripe redirect URI setting: ', 'wc-vendors-gateway-stripe-connect' ),
				get_permalink( $this->get_option( 'redirect_uri' ) ),
				__( 'Click the URI to select', 'wc-vendors-gateway-stripe-connect' )
			) : __( 'Select the page to redirect to after a vendor account is connected.', 'wc-vendors-gateway-stripe-connect' ),
			'options'     => $this->get_redirect_pages(),
		) : array(
			'title'       => __( 'Connect redirect page', 'wc-vendors-gateway-stripe-connect' ),
			'type'        => 'select',
			'description' => __( 'Select the page to redirect to after a vendor account is connected.', 'wc-vendors-gateway-stripe-connect' ),
			'options'     => $this->get_redirect_pages(),
		),
		'statement_descriptor'        => array(
			'title'       => __( 'Statement Descriptor', 'wc-vendors-gateway-stripe-connect' ),
			'type'        => 'text',
			'description' => __( 'This may be up to 22 characters. The statement description must contain at least one letter, may not include ><"\' characters, and will appear on your customer\'s statement in capital letters.', 'wc-vendors-gateway-stripe-connect' ),
			'default'     => '',
			'desc_tip'    => true,
		),
		'stripe_checkout'             => array(
			'title'       => __( 'Stripe Modal Checkout', 'wc-vendors-gateway-stripe-connect' ),
			'label'       => __( 'Enable Stripe Checkout', 'wc-vendors-gateway-stripe-connect' ),
			'type'        => 'checkbox',
			'description' => __( 'If enabled, this option shows a "pay" button and modal credit card form on the checkout, instead of credit card fields directly on the page.', 'wc-vendors-gateway-stripe-connect' ),
			'default'     => 'no',
			'desc_tip'    => true,
		),
		'stripe_checkout_image'       => array(
			'title'       => __( 'Stripe Checkout Image', 'wc-vendors-gateway-stripe-connect' ),
			'description' => __( 'Optionally enter the URL to a 128x128px image of your brand or product. e.g. <code>https://yoursite.com/wp-content/uploads/2013/09/yourimage.jpg</code>', 'wc-vendors-gateway-stripe-connect' ),
			'type'        => 'text',
			'default'     => '',
			'desc_tip'    => true,
		),
		'stripe_checkout_description' => array(
			'title'       => __( 'Stripe Checkout Description', 'wc-vendors-gateway-stripe-connect' ),
			'type'        => 'text',
			'description' => __( 'Shows a description of your store on Stripe Modal Checkout.', 'wc-vendors-gateway-stripe-connect' ),
			'default'     => '',
			'desc_tip'    => true,
		),
		'connect_button_theme'        => array(
			'title'       => __( 'Stripe Connect Button Theme', 'wc-vendors-gateway-stripe-connect' ),
			'label'       => __( 'Button Theme', 'wc-vendors-gateway-stripe-connect' ),
			'type'        => 'select',
			'description' => __( 'Select the button theme you would like to show.', 'wc-vendors-gateway-stripe-connect' ),
			'default'     => 'blue',
			'desc_tip'    => true,
			'options'     => array(
				'blue'              => __( 'Blue', 'wc-vendors-gateway-stripe-connect' ),
				'blue_border'       => __( 'Blue border', 'wc-vendors-gateway-stripe-connect' ),
				'light_blue'        => __( 'Light blue', 'wc-vendors-gateway-stripe-connect' ),
				'light_blue_border' => __( 'Light blue border', 'wc-vendors-gateway-stripe-connect' ),
			),
		),
		'saved_cards'                 => array(
			'title'       => __( 'Saved Cards', 'wc-vendors-gateway-stripe-connect' ),
			'label'       => __( 'Enable Payment via Saved Cards', 'wc-vendors-gateway-stripe-connect' ),
			'type'        => 'checkbox',
			'description' => __( 'If enabled, users will be able to pay with a saved card during checkout. Card details are saved on Stripe servers, not on your store.', 'wc-vendors-gateway-stripe-connect' ),
			'default'     => 'no',
			'desc_tip'    => true,
		),
		'require_connected_account'   => array(
			'title'   => __( 'Require connected account', 'wc-vendors-gateway-stripe-connect' ),
			'label'   => __( 'Require the vendors to connect their account before they can add products', 'wc-vendors-gateway-stripe-connect' ),
			'type'    => 'checkbox',
			'default' => 'no',
		),
		'disable_product_edit'        => array(
			'title'   => __( 'Disable edit', 'wc-vendors-gateway-stripe-connect' ),
			'label'   => __( 'Disable editing existing products if vendors have not connected their account. This is effective only when require connected account option is checked.', 'wc-vendors-gateway-stripe-connect' ),
			'type'    => 'checkbox',
			'default' => 'no',
		),
		'enable_logging'              => array(
			'title'       => __( 'Logging', 'wc-vendors-gateway-stripe-connect' ),
			'label'       => __( 'Log debugging messages', 'wc-vendors-gateway-stripe-connect' ),
			'type'        => 'checkbox',
			'description' => __( 'Enable writing to a log for for debugging. This is found in WooCommerce > Status > Logs', 'wc-vendors-gateway-stripe-connect' ),
			'default'     => 'no',
			'desc_tip'    => true,
		),
		'enable_charges_transfers'    => array(
			'title'       => __( 'Use Stripe Separate Charges and Transfers (US/EU)', 'wc-vendors-gateway-stripe-connect' ),
			'label'       => __( 'Enable Separate Charges and Transfers', 'wc-vendors-gateway-stripe-connect' ),
			'type'        => 'checkbox',
			'description' => __( 'Check this option to enable Separate Charges and Transfers which allows more advanced payment features including 3D Secure Card. This option is available for US/EU marketplace only.', 'wc-vendors-gateway-stripe-connect' ),
			'default'     => 'no',
			'desc_tip'    => true,
		),
		'disable_refund'              => array(
			'title'   => __( 'Disable Refund', 'wc-vendors-gateway-stripe-connect' ),
			'label'   => __( 'Disable Refund and Refund request functionalities.', 'wc-vendors-gateway-stripe-connect' ),
			'type'    => 'checkbox',
			'default' => 'no',
		),
	)
);
